### PR TITLE
Request to merge 5G on Arm handbook into main

### PR DESCRIPTION
**Pull request by westlaker**
Before submitting a pull request for a new Learning Path, please review [Create a Learning Path](https://learn.arm.com//learning-paths/cross-platform/_example-learning-path/)
- [ x] I have reviewed Create a Learning Path

Please do not include any confidential information in your contribution. This includes confidential microarchitecture details and unannounced product information.
- [ x] I have checked my contribution for confidential information

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the Creative Commons Attribution 4.0 International License.

### CODE REVIEW

**Comment by pareenaverma** [comment]
Thank you @westlaker for your contribution. I have started to review this LP and made a few changes. A lot of acronyms are used throughout this learning path which aren't introduced. Can you please add some context for the reader along with the expansion for these acronyms before the first usage? Thanks

**Review by westlaker — COMMENTED** [review]
I should not be the author as we worked on this as a team, many of team members contributed to this content.

everything else looks good.

thanks

**Comment by pareenaverma** [comment]
Hi @westlaker in how-to-2.md can you please add some additional context/information in "Creating SR-IOV Resources" section.  It's not clear what the code shown below is: is it a file that the user needs to create? a configuration map?

**Comment by pareenaverma** [comment]
Can you also clarify what the exact command to be run here is
"Execute the following command to append iommu.passthrough=1 option. GRUB_CMLINE_LINUX in /etc/default/grub"

**Comment by pareenaverma** [comment]
In the "SR-IOV CNI Resource Verification" section, there is a line at the end that says "This command displays the following sample output." but there is no output there.

**Comment by pareenaverma** [comment]
In how-to-3.md under "System level setting" it says slc_inst_s0 script can be found in attachment:   slc_inst_s0 
can you either add the script contents to the learning path or a pointer to where this script contents can be found?

**Comment by westlaker** [comment]
> slc_inst_s0

**Comment by westlaker** [comment]
> In how-to-3.md under "System level setting" it says slc_inst_s0 script can be found in attachment: slc_inst_s0 can you either add the script contents to the learning path or a pointer to where this script contents can be found?

actually the slc_inst_s0 is a program not a script. not sure what to do with it here

**Comment by westlaker** [comment]
I had just addressed your comments with another commit. Is it possible to make ```console expandable by clicking?
thanks for your sharp eyes!

**Pull request closed without merging**
