### PR TITLE
add steps to enable mysql pgo

### PR DESCRIPTION
**Pull request by boltliu85**
Before submitting a pull request for a new Learning Path, please review [Create a Learning Path](https://learn.arm.com//learning-paths/cross-platform/_example-learning-path/)
- [x] I have reviewed Create a Learning Path

Please do not include any confidential information in your contribution. This includes confidential microarchitecture details and unannounced product information.
- [x] I have checked my contribution for confidential information

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the Creative Commons Attribution 4.0 International License.

### CODE REVIEW

**Comment by boltliu85** [comment]
> Hi @boltliu85 Thank you for your contribution. Can you add more instructions about how to start the MySQL server and run the benchmark tests? I'm not clear on the commands to run. Thank you.

Hi Jason, since this is an advanced topic regarding increase MySQL performance, the instructions to start MySQL server and run benchmark tests are prerequisites for this topic, hence not covered here.

I would assume there should already be a learning path about the methods to start MySQL server and run benchmark since it's very common and basis for performance tuning of MySQL (also applicable for other tuning methods), if it's not the case, I could create another learning path for it. how do you think?

**Comment by jasonrandrews** [comment]
Thanks, @boltliu85, I understand. I'll start the review and will add the assumed knowledge.

**Comment by jasonrandrews** [comment]
Hi @boltliu85 I have combined the PGO instructions in the mysql_server Learning Path. This way, a reader can follow the original setup and continue on with PGO all in 1 Learning Path. Please check now that mysql_server has everything needed. If you see any mistakes, please feel free to submit a new PR.

**Comment by boltliu85** [comment]
> Hi @boltliu85 I have combined the PGO instructions in the mysql_server Learning Path. This way, a reader can follow the original setup and continue on with PGO all in 1 Learning Path. Please check now that mysql_server has everything needed. If you see any mistakes, please feel free to submit a new PR.

OK, thanks!

**Pull request closed without merging**
