### PR TITLE
Update acfl.md for 23.10 release version

### PR DESCRIPTION
**Pull request by managa02**
Before submitting a pull request for a new Learning Path, please review [Create a Learning Path](https://learn.arm.com//learning-paths/cross-platform/_example-learning-path/)
- [ ] I have reviewed Create a Learning Path

Please do not include any confidential information in your contribution. This includes confidential microarchitecture details and unannounced product information.
- [ ] I have checked my contribution for confidential information

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the Creative Commons Attribution 4.0 International License.

### CODE REVIEW

**Comment by pareenaverma** [comment]
Hi @managa02 - thanks for the update to the versions. The PR is currently set to "draft". Please let us know if you're ready for it to be reviewed and merged? Thanks

**Comment by managa02** [comment]
HI @pareenaverma , I have made few changes in the document.Please let me know if you have any questions.

**Comment by managa02** [comment]
@pareenaverma  Please do not submit/merge this pull request until we release the product 23.10 version which due in october 2023.
This PR is only sent for review purpose and to be merge once we release our 23.10 version.

**Comment by pareenaverma** [comment]
Thank you. The updates look good. We'll be on the lookout for the release but please update this PR with a comment when it is.

**Pull request merged**
