### PR TITLE
Profiling firmware with pmu

### PR DESCRIPTION
**Pull request by Jiaming97**
Before submitting a pull request for a new Learning Path, please review [Create a Learning Path](https://learn.arm.com//learning-paths/cross-platform/_example-learning-path/)
- [x] I have reviewed Create a Learning Path

Please do not include any confidential information in your contribution. This includes confidential microarchitecture details and unannounced product information.
- [x] I have checked my contribution for confidential information

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the Creative Commons Attribution 4.0 International License.

### CODE REVIEW

**Comment by pareenaverma** [comment]
Thank you @Jiaming97 for your contribution.
I have a few questions: 
1. Is the PMU library implementation (all the files) hosted in a public repo already elsewhere?
It's better to have the learning path reference code hosted in a repo rather than hosting the code in the learning path repo itself. If it was just small code snippets that would be fine to reference here but in this case it's a collection of files. 
2. For both the TF-A and U-boot examples can you please outline the complete steps for a user to get the source, make the changes to the Makefile/source, build the binaries and then run the binaries on a platform(I believe juno). You can break these two examples into separate how-to sections. Please highlight the platform the reader requires to run the software example on.

**Comment by pareenaverma** [comment]
Hi @Jiaming97, for hosting open source code projects there's a public gitlab instance: https://confluence.arm.com/display/BSGSoftware/User+Guide:+External+GitLab 

Do you know if the source code files you've shared here are from an already existing example or library somewhere or did you write this code from scratch?

**Comment by Jiaming97** [comment]
Hi @pareenaverma, 
Thank you for providing the information. I've reviewed the requirements, and I believe it's essential to consult with the team about seeking Anaqua approval. 

In my source code, I've reused "arch.h" and "arch_helpers.h" from TF-A, while the remaining source files are my own work.

Also, do you think it a good idea if I divide this learning path to two learning paths. One is for the PMU library implementation, which is focusing on enabling PMU. The other is for using the PMU library to profile, similar to the existing learning path?

**Comment by Jiaming97** [comment]
Hi @pareenaverma ,
After the discussion with my team manager, we have decided to attempt posting this article on the Arm Community, where we can upload the PMU library as an attachment. Consequently, I will close this pull request. Thank you once again for your review.

**Pull request closed without merging**
