### PR TITLE
Update title

### PR DESCRIPTION
**Pull request by odidev**
- Updated title of **azure_terraform** section
- Updated title of **gcp** section

### CODE REVIEW

**Comment by jasonrandrews** [comment]
Hi @odidev Using acronyms in the titles is not ideal as some readers may not be familiar. Is there a reason you want to use them? I'm wondering if you are trying to make the search box easier because it only searches title, and it would be easier to type an acronym when searching.

**Comment by jsrz** [comment]
Hi @jasonrandrews 

Part of it was for making search either, part of it is that often people think GCP (or AWS) before they think of the full name.  In fact, I didn't even know what the acronym GCP meant initially.

Concern was discoverability might be hindered without it.

That said, if you'd rather not have that, we can drop this PR then.

**Comment by jasonrandrews** [comment]
@jsrz Thanks for the background. I'm happy to merge if you use parenthesis with acronyms to improve the search. 

Can you modify to become:
Deploy Arm virtual machines (VMs) on Azure with Terraform
Deploy Arm virtual machines (VMs) on Google Cloud Platform (GCP)

If you can also check for other Learning Paths with Google Cloud in the title and add the GCP it would be much appreciated.

**Comment by odidev** [comment]
@jsrz, I will check and update PR accordingly.

**Comment by jsrz** [comment]
@odidev thanks.

I think for this PR, it just needs to read:
 Deploy Arm virtual machines on Google Cloud Platform (GCP)

The Azure update can be dropped.

**Pull request merged**
